# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rails-up"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Russ Smith", "Gabriel Evans"]
  s.date = "2012-01-13"
  s.description = "Automatic vagrant box for your rails project."
  s.email = ["russ@bashme.org", "gabriel@codeconcoction.com"]
  s.executables = ["rails-up"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".gitmodules",
    ".rspec",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/rails-up",
    "components/apt_component.rb",
    "components/mongodb_component.rb",
    "components/redis_component.rb",
    "components/rvm_component.rb",
    "lib/rails-up.rb",
    "lib/rails-up/actions.rb",
    "lib/rails-up/component.rb",
    "lib/rails-up/component_builder.rb",
    "lib/rails-up/components.rb",
    "lib/rails-up/components/role.rb",
    "lib/rails-up/components/role_builder.rb",
    "lib/rails-up/errors.rb",
    "lib/rails-up/version.rb",
    "rails-up.gemspec",
    "spec/component_builder_spec.rb",
    "spec/component_spec.rb",
    "spec/components/role_spec.rb",
    "spec/components_spec.rb",
    "spec/rails-up_spec.rb",
    "spec/spec_helper.rb",
    "templates/Cheffile",
    "templates/Vagrantfile.tt",
    "templates/chef/cookbooks/application/recipes/application.rb",
    "templates/chef/cookbooks/application/recipes/database.rb",
    "templates/chef/cookbooks/application/recipes/user.rb",
    "templates/chef/cookbooks/application/templates/default/application.init.erb",
    "templates/chef/cookbooks/apt/README.md",
    "templates/chef/cookbooks/apt/files/default/apt-cacher",
    "templates/chef/cookbooks/apt/files/default/apt-cacher.conf",
    "templates/chef/cookbooks/apt/files/default/apt-proxy-v2.conf",
    "templates/chef/cookbooks/apt/metadata.json",
    "templates/chef/cookbooks/apt/metadata.rb",
    "templates/chef/cookbooks/apt/providers/repository.rb",
    "templates/chef/cookbooks/apt/recipes/cacher-client.rb",
    "templates/chef/cookbooks/apt/recipes/cacher.rb",
    "templates/chef/cookbooks/apt/recipes/default.rb",
    "templates/chef/cookbooks/apt/resources/repository.rb",
    "templates/chef/cookbooks/build-essential/README.md",
    "templates/chef/cookbooks/build-essential/metadata.json",
    "templates/chef/cookbooks/build-essential/metadata.rb",
    "templates/chef/cookbooks/build-essential/recipes/default.rb",
    "templates/chef/cookbooks/imagemagick/README.rdoc",
    "templates/chef/cookbooks/imagemagick/metadata.json",
    "templates/chef/cookbooks/imagemagick/metadata.rb",
    "templates/chef/cookbooks/imagemagick/recipes/default.rb",
    "templates/chef/cookbooks/imagemagick/recipes/rmagick.rb",
    "templates/chef/cookbooks/nginx/README.md",
    "templates/chef/cookbooks/nginx/attributes/default.rb",
    "templates/chef/cookbooks/nginx/definitions/nginx_site.rb",
    "templates/chef/cookbooks/nginx/files/default/mime.types",
    "templates/chef/cookbooks/nginx/metadata.json",
    "templates/chef/cookbooks/nginx/metadata.rb",
    "templates/chef/cookbooks/nginx/recipes/default.rb",
    "templates/chef/cookbooks/nginx/recipes/source.rb",
    "templates/chef/cookbooks/nginx/templates/default/default-site.erb",
    "templates/chef/cookbooks/nginx/templates/default/nginx.conf.erb",
    "templates/chef/cookbooks/nginx/templates/default/nginx.init.erb",
    "templates/chef/cookbooks/nginx/templates/default/nginx.sysconfig.erb",
    "templates/chef/cookbooks/nginx/templates/default/nxdissite.erb",
    "templates/chef/cookbooks/nginx/templates/default/nxensite.erb",
    "templates/chef/cookbooks/nginx/templates/default/sv-nginx-log-run.erb",
    "templates/chef/cookbooks/nginx/templates/default/sv-nginx-run.erb",
    "templates/chef/cookbooks/postgresql/attributes/server.rb",
    "templates/chef/cookbooks/postgresql/libraries/database.rb",
    "templates/chef/cookbooks/postgresql/providers/database.rb",
    "templates/chef/cookbooks/postgresql/recipes/client.rb",
    "templates/chef/cookbooks/postgresql/recipes/default.rb",
    "templates/chef/cookbooks/postgresql/recipes/server.rb",
    "templates/chef/cookbooks/postgresql/resources/database.rb",
    "templates/chef/cookbooks/postgresql/templates/default/grants.sql.erb",
    "templates/chef/cookbooks/postgresql/templates/default/pg_hba.conf.erb",
    "templates/chef/cookbooks/postgresql/templates/default/postgresql.conf.erb",
    "templates/chef/cookbooks/redis/attributes/redis.rb",
    "templates/chef/cookbooks/redis/metadata.json",
    "templates/chef/cookbooks/redis/metadata.rb",
    "templates/chef/cookbooks/redis/recipes/source.rb",
    "templates/chef/cookbooks/redis/templates/default/redis.conf.erb",
    "templates/chef/cookbooks/redis/templates/default/redis.init.erb",
    "templates/chef/cookbooks/runit/attributes/default.rb",
    "templates/chef/cookbooks/runit/definitions/runit_service.rb",
    "templates/chef/cookbooks/runit/files/default/runit.seed",
    "templates/chef/cookbooks/runit/files/default/runsvdir",
    "templates/chef/cookbooks/runit/files/ubuntu-6.10/runsvdir",
    "templates/chef/cookbooks/runit/files/ubuntu-7.04/runsvdir",
    "templates/chef/cookbooks/runit/files/ubuntu-7.10/runsvdir",
    "templates/chef/cookbooks/runit/files/ubuntu-8.04/runsvdir",
    "templates/chef/cookbooks/runit/metadata.json",
    "templates/chef/cookbooks/runit/metadata.rb",
    "templates/chef/cookbooks/runit/recipes/default.rb",
    "templates/chef/cookbooks/runit/templates/gentoo/runit-start.sh.erb",
    "templates/chef/cookbooks/rvm/.gitignore",
    "templates/chef/cookbooks/rvm/CHANGELOG.md",
    "templates/chef/cookbooks/rvm/README.md",
    "templates/chef/cookbooks/rvm/Rakefile",
    "templates/chef/cookbooks/rvm/attributes/.gitkeep",
    "templates/chef/cookbooks/rvm/attributes/default.rb",
    "templates/chef/cookbooks/rvm/attributes/gem_package.rb",
    "templates/chef/cookbooks/rvm/attributes/vagrant.rb",
    "templates/chef/cookbooks/rvm/libraries/gem_package_monkeypatch.rb",
    "templates/chef/cookbooks/rvm/libraries/helpers.rb",
    "templates/chef/cookbooks/rvm/libraries/rvm_chef_shell_wrapper.rb",
    "templates/chef/cookbooks/rvm/libraries/rvm_rubygems_package.rb",
    "templates/chef/cookbooks/rvm/metadata.json",
    "templates/chef/cookbooks/rvm/metadata.rb",
    "templates/chef/cookbooks/rvm/providers/default_ruby.rb",
    "templates/chef/cookbooks/rvm/providers/environment.rb",
    "templates/chef/cookbooks/rvm/providers/gemset.rb",
    "templates/chef/cookbooks/rvm/providers/global_gem.rb",
    "templates/chef/cookbooks/rvm/providers/ruby.rb",
    "templates/chef/cookbooks/rvm/providers/shell.rb",
    "templates/chef/cookbooks/rvm/providers/wrapper.rb",
    "templates/chef/cookbooks/rvm/recipes/.gitkeep",
    "templates/chef/cookbooks/rvm/recipes/default.rb",
    "templates/chef/cookbooks/rvm/recipes/gem_package.rb",
    "templates/chef/cookbooks/rvm/recipes/system.rb",
    "templates/chef/cookbooks/rvm/recipes/vagrant.rb",
    "templates/chef/cookbooks/rvm/resources/default_ruby.rb",
    "templates/chef/cookbooks/rvm/resources/environment.rb",
    "templates/chef/cookbooks/rvm/resources/gem.rb",
    "templates/chef/cookbooks/rvm/resources/gemset.rb",
    "templates/chef/cookbooks/rvm/resources/global_gem.rb",
    "templates/chef/cookbooks/rvm/resources/ruby.rb",
    "templates/chef/cookbooks/rvm/resources/shell.rb",
    "templates/chef/cookbooks/rvm/resources/wrapper.rb",
    "templates/chef/cookbooks/rvm/templates/default/rvmrc.erb",
    "templates/chef/cookbooks/rvm/templates/default/vagrant-chef-solo-wrapper.erb",
    "templates/chef/cookbooks/varnish/attributes/varnish.rb",
    "templates/chef/cookbooks/varnish/metadata.json",
    "templates/chef/cookbooks/varnish/metadata.rb",
    "templates/chef/cookbooks/varnish/recipes/default.rb",
    "templates/chef/roles/application.rb",
    "templates/chef/roles/base.rb",
    "templates/chef/roles/database.rb",
    "templates/chef/roles/nginx.rb",
    "templates/chef/roles/redis.rb",
    "templates/chef/roles/varnish.rb"
  ]
  s.homepage = "http://github.com/russ/rails-up"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Automatic vagrant box for your rails project."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thor>, ["~> 0.14.6"])
      s.add_runtime_dependency(%q<librarian>, ["~> 0.0.12"])
      s.add_runtime_dependency(%q<chef>, [">= 0.10.8"])
      s.add_runtime_dependency(%q<vagrant>, [">= 0.8.7"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_development_dependency(%q<rspec>, ["~> 2.7.0"])
      s.add_development_dependency(%q<spork>, ["~> 0.8.5"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<guard>, ["~> 0.8.8"])
      s.add_development_dependency(%q<guard-bundler>, ["~> 0.1.3"])
      s.add_development_dependency(%q<guard-rspec>, ["~> 0.5.8"])
      s.add_development_dependency(%q<guard-spork>, ["~> 0.3.2"])
      s.add_development_dependency(%q<rb-fsevent>, [">= 0"])
      s.add_development_dependency(%q<growl>, [">= 0"])
    else
      s.add_dependency(%q<thor>, ["~> 0.14.6"])
      s.add_dependency(%q<librarian>, ["~> 0.0.12"])
      s.add_dependency(%q<chef>, [">= 0.10.8"])
      s.add_dependency(%q<vagrant>, [">= 0.8.7"])
      s.add_dependency(%q<activesupport>, [">= 2.3.5"])
      s.add_dependency(%q<rspec>, ["~> 2.7.0"])
      s.add_dependency(%q<spork>, ["~> 0.8.5"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<guard>, ["~> 0.8.8"])
      s.add_dependency(%q<guard-bundler>, ["~> 0.1.3"])
      s.add_dependency(%q<guard-rspec>, ["~> 0.5.8"])
      s.add_dependency(%q<guard-spork>, ["~> 0.3.2"])
      s.add_dependency(%q<rb-fsevent>, [">= 0"])
      s.add_dependency(%q<growl>, [">= 0"])
    end
  else
    s.add_dependency(%q<thor>, ["~> 0.14.6"])
    s.add_dependency(%q<librarian>, ["~> 0.0.12"])
    s.add_dependency(%q<chef>, [">= 0.10.8"])
    s.add_dependency(%q<vagrant>, [">= 0.8.7"])
    s.add_dependency(%q<activesupport>, [">= 2.3.5"])
    s.add_dependency(%q<rspec>, ["~> 2.7.0"])
    s.add_dependency(%q<spork>, ["~> 0.8.5"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<guard>, ["~> 0.8.8"])
    s.add_dependency(%q<guard-bundler>, ["~> 0.1.3"])
    s.add_dependency(%q<guard-rspec>, ["~> 0.5.8"])
    s.add_dependency(%q<guard-spork>, ["~> 0.3.2"])
    s.add_dependency(%q<rb-fsevent>, [">= 0"])
    s.add_dependency(%q<growl>, [">= 0"])
  end
end

